###############################
###############################
service: serverlesscatalogs

plugins:
  - serverless-python-requirements
    #custom:
    #  pythonRequirements:
    #    zip: true
custom:
  pythonRequirements:
    dockerizePip: non-linux
    pythonBin:  /usr/bin/python3

    #package:
    #    excludeDevDependencies: true

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-west-2
  memorySize: 3008 # Overwrite the default memory size. Default is 1024
  #role: arn:aws:iam::938975972071:role/service-role/PUB_catalog_role
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : "serverlesscatalogs"
            - "/*"

# También poner de dónde consume la lambda

functions:
  monthlycatalog:
    handler: pub_handler.CatalogPub
    events:
      - s3:
          bucket: serverlesscatalogs
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv

resources:
  Resources:
    serverlesscatalogs:
      Type: AWS::S3::Bucket
      Properties:
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
              AllowedOrigins:
                - "*"
