###############################
###############################
service: serverlesscatalogs2

package:
  individually: True
  exclude:
    # Exclude everything first.
    - '**/*'

plugins:
  - serverless-python-individually
  - serverless-python-requirements
    #custom:
    #  pythonRequirements:
    #    zip: true

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-west-2
  memorySize: 3008 # Overwrite the default memory size. Default is 1024
  role: arn:aws:iam::938975972071:role/service-role/PUB_catalog_role
  #  iamRoleStatements:
  #    - Effect: "Allow"
  #      Action:
  #        - "s3:*"
  #      Resource:
  #        Fn::Join:
  #          - ""
  #          - - "arn:aws:s3:::"
  #            - "Ref" : "serverlesscatalogs"
  #            - "/*"
  #

functions:
  cuaps-pub-catalog:
    handler: cuaps-pub/wrap.handler #.CatalogPub
    package:
      include:
        - cuaps-pub/**
    events:
      - s3:
          bucket: serverlesscatalogs
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv

#  pub-monthly:
#    handler: pub-monthly/wrap.handler #.CatalogPub
#    package:
#      include:
#        - pub-monthly/**
#

custom:
  pyIndividually:
    wrap:cuapsFunc: cuaps-pub/handler.catalog_creation
    wrap:pubFunnc: pub-monthly/handler.catalog_creation
  pythonRequirements:
    dockerizePip: non-linux
    pythonBin:  /usr/bin/python3
    #package:
    #    excludeDevDependencies: true


resources:
  Resources:
    serverlesscatalogs:
      Type: AWS::S3::Bucket
      Properties:
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
              AllowedOrigins:
                - "*"
