###############################
###############################
service: serverlesscatalogs

package:
  individually: True
  exclude:
    # Exclude everything first.
    - '**/*'
    - secrets.yml

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-west-2
  memorySize: 3008 # Overwrite the default memory size. Default is 1024
  #role: arn:aws:iam::938975972071:role/service-role/PUB_catalog_role
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - "s3:*"
      Resource: "*"
  environment:
    HOST_ES: "${self:custom.secrets.HOST_ES}"

functions:
  cuaps-pub:
    handler: cuaps-pub/wrap.handler
    package:
      include:
        - cuaps-pub/**
    events:
      - s3:
          bucket: serverlesscatalogs
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv

#  pub-monthly:
#    handler: pub-monthly/wrap.handler
#    package:
#      include:
#        - pub-monthly/**
#

custom:
  pyIndividually:
    wrap:cuaps-pub: cuaps-pub/handler.catalog
    #wrap:pubFunnc: pub-monthly/handler.catalog_creation
    #  pythonRequirements:
    #    zip: true
    #    dockerizePip: non-linux
    #    pythonBin:  /usr/bin/python3
    #    #package:
    #    #    excludeDevDependencies: true
  stage: ${opt:stage, self:provider.stage}
  secrets: ${file(secrets.yml):${self:custom.stage}}

resources:
  Resources:
    serverlesscatalogs:
      Type: AWS::S3::Bucket
      Properties:
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
              AllowedOrigins:
                - "*"

plugins:
  - serverless-python-individually
    #- serverless-python-requirements
    #custom:
    #  pythonRequirements:
    #    zip: true
