###################################
###################################

service: Pub-Pub-Serverless

plugins:
    - serverless-plugin-existing-s3
    - serverless-package-python-functions

custom:
  pkgPyFuncs:
    #requirementsFile: requirements.txt 
    #globalRequirements: 
    #  - ./globalRequirements.txt
    #globalIncludes: 
    #  - ./common
    buildDir: _build 
    cleanup: true 


provider:
    name: aws
    runtime: python3.6
    # stage: dev
    region: us-west-2
    # role: arn:aws:iam::938975972071:role/service-role/PUB_catalog_role
    iamRoleStatements:
        - Effect: "Allow"
          Action:
              - "*"
          Resource:
              Fn::Join:
                  - ""
                  - - "arn:aws:s3:::publicaciones-sedesol"
functions:
    MonthlyCatalogPub:
        handler: src/pub_handler.MonthlyCatalogPub
        event:
            - existingS3:
                bucket: publicaciones-sedesol 
                events:
                    - s3:ObjectCreated:* 
                rules:
                    - prefix: /catalogo_mensual/
                    - suffix: catalogo_mensual.csv 
        package:
            include:
                - src
            exclude:
                - secrets.yaml 

#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
