emr:
    region_name: us-west-2
    cluster_name: ppreventiva_cluster
    instance_count: 4
    master_instance_type: c3.4xlarge
    slave_instance_type:  c3.4xlarge
    key_name: proyecto_sdv
    subnet_id: subnet-68dfb130
    log_uri: s3://spark-sedesol/logs/emr-logs/
    software_version: emr-5.11.1
    key: pub
    key_value: pub_sedesol
